name: Build and Push NGINX Image (Latest)

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

permissions:
  packages: write  # Grant write access to GitHub packages (GHCR)
  contents: read   # Grant read access to repository contents

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Git (for commit hash)
      run: sudo apt-get install git

    - name: Update HTML with Commit Info
      run: ./scripts/update_commit_info.sh

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker Image
      run: |
        # Convert the repository owner to lowercase
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

        # Always use the "latest" tag
        TAG=latest

        # Build the Docker image
        docker build -t ghcr.io/$REPO_OWNER/nginx-test:$TAG .

    - name: Push Docker Image to GHCR
      run: |
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        TAG=latest

        # Push the Docker image
        docker push ghcr.io/$REPO_OWNER/nginx-test:$TAG
