name: Build and Push Multi-Architecture NGINX Image (Latest)

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

permissions:
  packages: write  # Grant write access to GitHub packages (GHCR)
  contents: read   # Grant read access to repository contents

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create and boot Buildx builder
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap

    - name: Install Git (for commit hash)
      run: sudo apt-get install git

    - name: Update HTML with Commit Info
      run: ./scripts/update_commit_info.sh

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Multi-Arch Docker Image
      run: |
        # Convert the repository owner to lowercase
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

        # Always use the "latest" tag
        TAG=latest

        # Build and push the Docker image for both amd64 and arm64 platforms
        docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/$REPO_OWNER/nginx-test:$TAG --push .
